// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/influenzanet/study-service/pkg/api (interfaces: StudyServiceApiClient)
//
// Generated by this command:
//
//	mockgen github.com/influenzanet/study-service/pkg/api StudyServiceApiClient
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	api_types "github.com/influenzanet/go-utils/pkg/api_types"
	api "github.com/influenzanet/study-service/pkg/api"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockStudyServiceApiClient is a mock of StudyServiceApiClient interface.
type MockStudyServiceApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockStudyServiceApiClientMockRecorder
	isgomock struct{}
}

// MockStudyServiceApiClientMockRecorder is the mock recorder for MockStudyServiceApiClient.
type MockStudyServiceApiClientMockRecorder struct {
	mock *MockStudyServiceApiClient
}

// NewMockStudyServiceApiClient creates a new mock instance.
func NewMockStudyServiceApiClient(ctrl *gomock.Controller) *MockStudyServiceApiClient {
	mock := &MockStudyServiceApiClient{ctrl: ctrl}
	mock.recorder = &MockStudyServiceApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudyServiceApiClient) EXPECT() *MockStudyServiceApiClientMockRecorder {
	return m.recorder
}

// ConvertTemporaryToParticipant mocks base method.
func (m *MockStudyServiceApiClient) ConvertTemporaryToParticipant(ctx context.Context, in *api.ConvertTempParticipantReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConvertTemporaryToParticipant", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertTemporaryToParticipant indicates an expected call of ConvertTemporaryToParticipant.
func (mr *MockStudyServiceApiClientMockRecorder) ConvertTemporaryToParticipant(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertTemporaryToParticipant", reflect.TypeOf((*MockStudyServiceApiClient)(nil).ConvertTemporaryToParticipant), varargs...)
}

// CreateNewStudy mocks base method.
func (m *MockStudyServiceApiClient) CreateNewStudy(ctx context.Context, in *api.NewStudyRequest, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateNewStudy", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewStudy indicates an expected call of CreateNewStudy.
func (mr *MockStudyServiceApiClientMockRecorder) CreateNewStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).CreateNewStudy), varargs...)
}

// CreateReport mocks base method.
func (m *MockStudyServiceApiClient) CreateReport(ctx context.Context, in *api.CreateReportReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateReport", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockStudyServiceApiClientMockRecorder) CreateReport(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockStudyServiceApiClient)(nil).CreateReport), varargs...)
}

// DeleteMessagesFromParticipant mocks base method.
func (m *MockStudyServiceApiClient) DeleteMessagesFromParticipant(ctx context.Context, in *api.DeleteMessagesFromParticipantReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMessagesFromParticipant", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessagesFromParticipant indicates an expected call of DeleteMessagesFromParticipant.
func (mr *MockStudyServiceApiClientMockRecorder) DeleteMessagesFromParticipant(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessagesFromParticipant", reflect.TypeOf((*MockStudyServiceApiClient)(nil).DeleteMessagesFromParticipant), varargs...)
}

// DeleteParticipantData mocks base method.
func (m *MockStudyServiceApiClient) DeleteParticipantData(ctx context.Context, in *api_types.TokenInfos, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteParticipantData", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteParticipantData indicates an expected call of DeleteParticipantData.
func (mr *MockStudyServiceApiClientMockRecorder) DeleteParticipantData(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParticipantData", reflect.TypeOf((*MockStudyServiceApiClient)(nil).DeleteParticipantData), varargs...)
}

// DeleteParticipantFiles mocks base method.
func (m *MockStudyServiceApiClient) DeleteParticipantFiles(ctx context.Context, in *api.DeleteParticipantFilesReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteParticipantFiles", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteParticipantFiles indicates an expected call of DeleteParticipantFiles.
func (mr *MockStudyServiceApiClientMockRecorder) DeleteParticipantFiles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParticipantFiles", reflect.TypeOf((*MockStudyServiceApiClient)(nil).DeleteParticipantFiles), varargs...)
}

// DeleteResearcherMessages mocks base method.
func (m *MockStudyServiceApiClient) DeleteResearcherMessages(ctx context.Context, in *api.DeleteResearcherMessagesReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteResearcherMessages", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteResearcherMessages indicates an expected call of DeleteResearcherMessages.
func (mr *MockStudyServiceApiClientMockRecorder) DeleteResearcherMessages(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResearcherMessages", reflect.TypeOf((*MockStudyServiceApiClient)(nil).DeleteResearcherMessages), varargs...)
}

// DeleteStudy mocks base method.
func (m *MockStudyServiceApiClient) DeleteStudy(ctx context.Context, in *api.StudyReferenceReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStudy", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStudy indicates an expected call of DeleteStudy.
func (mr *MockStudyServiceApiClientMockRecorder) DeleteStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).DeleteStudy), varargs...)
}

// EnterStudy mocks base method.
func (m *MockStudyServiceApiClient) EnterStudy(ctx context.Context, in *api.EnterStudyRequest, opts ...grpc.CallOption) (*api.AssignedSurveys, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnterStudy", varargs...)
	ret0, _ := ret[0].(*api.AssignedSurveys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnterStudy indicates an expected call of EnterStudy.
func (mr *MockStudyServiceApiClientMockRecorder) EnterStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).EnterStudy), varargs...)
}

// GetActiveStudies mocks base method.
func (m *MockStudyServiceApiClient) GetActiveStudies(ctx context.Context, in *api_types.TokenInfos, opts ...grpc.CallOption) (*api.Studies, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetActiveStudies", varargs...)
	ret0, _ := ret[0].(*api.Studies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveStudies indicates an expected call of GetActiveStudies.
func (mr *MockStudyServiceApiClientMockRecorder) GetActiveStudies(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveStudies", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetActiveStudies), varargs...)
}

// GetAllStudies mocks base method.
func (m *MockStudyServiceApiClient) GetAllStudies(ctx context.Context, in *api_types.TokenInfos, opts ...grpc.CallOption) (*api.Studies, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllStudies", varargs...)
	ret0, _ := ret[0].(*api.Studies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStudies indicates an expected call of GetAllStudies.
func (mr *MockStudyServiceApiClientMockRecorder) GetAllStudies(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStudies", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetAllStudies), varargs...)
}

// GetAssignedSurvey mocks base method.
func (m *MockStudyServiceApiClient) GetAssignedSurvey(ctx context.Context, in *api.SurveyReferenceRequest, opts ...grpc.CallOption) (*api.SurveyAndContext, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAssignedSurvey", varargs...)
	ret0, _ := ret[0].(*api.SurveyAndContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedSurvey indicates an expected call of GetAssignedSurvey.
func (mr *MockStudyServiceApiClientMockRecorder) GetAssignedSurvey(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedSurvey", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetAssignedSurvey), varargs...)
}

// GetAssignedSurveys mocks base method.
func (m *MockStudyServiceApiClient) GetAssignedSurveys(ctx context.Context, in *api_types.TokenInfos, opts ...grpc.CallOption) (*api.AssignedSurveys, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAssignedSurveys", varargs...)
	ret0, _ := ret[0].(*api.AssignedSurveys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedSurveys indicates an expected call of GetAssignedSurveys.
func (mr *MockStudyServiceApiClientMockRecorder) GetAssignedSurveys(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedSurveys", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetAssignedSurveys), varargs...)
}

// GetAssignedSurveysForTemporaryParticipant mocks base method.
func (m *MockStudyServiceApiClient) GetAssignedSurveysForTemporaryParticipant(ctx context.Context, in *api.GetAssignedSurveysForTemporaryParticipantReq, opts ...grpc.CallOption) (*api.AssignedSurveys, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAssignedSurveysForTemporaryParticipant", varargs...)
	ret0, _ := ret[0].(*api.AssignedSurveys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedSurveysForTemporaryParticipant indicates an expected call of GetAssignedSurveysForTemporaryParticipant.
func (mr *MockStudyServiceApiClientMockRecorder) GetAssignedSurveysForTemporaryParticipant(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedSurveysForTemporaryParticipant", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetAssignedSurveysForTemporaryParticipant), varargs...)
}

// GetConfidentialResponses mocks base method.
func (m *MockStudyServiceApiClient) GetConfidentialResponses(ctx context.Context, in *api.ConfidentialResponsesQuery, opts ...grpc.CallOption) (*api.ConfidentialResponses, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConfidentialResponses", varargs...)
	ret0, _ := ret[0].(*api.ConfidentialResponses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfidentialResponses indicates an expected call of GetConfidentialResponses.
func (mr *MockStudyServiceApiClientMockRecorder) GetConfidentialResponses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfidentialResponses", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetConfidentialResponses), varargs...)
}

// GetCurrentStudyRules mocks base method.
func (m *MockStudyServiceApiClient) GetCurrentStudyRules(ctx context.Context, in *api.StudyReferenceReq, opts ...grpc.CallOption) (*api.StudyRules, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCurrentStudyRules", varargs...)
	ret0, _ := ret[0].(*api.StudyRules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentStudyRules indicates an expected call of GetCurrentStudyRules.
func (mr *MockStudyServiceApiClientMockRecorder) GetCurrentStudyRules(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentStudyRules", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetCurrentStudyRules), varargs...)
}

// GetParticipantFile mocks base method.
func (m *MockStudyServiceApiClient) GetParticipantFile(ctx context.Context, in *api.GetParticipantFileReq, opts ...grpc.CallOption) (api.StudyServiceApi_GetParticipantFileClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParticipantFile", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_GetParticipantFileClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantFile indicates an expected call of GetParticipantFile.
func (mr *MockStudyServiceApiClientMockRecorder) GetParticipantFile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantFile", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetParticipantFile), varargs...)
}

// GetParticipantMessages mocks base method.
func (m *MockStudyServiceApiClient) GetParticipantMessages(ctx context.Context, in *api.GetParticipantMessagesReq, opts ...grpc.CallOption) (*api.StudyMessages, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParticipantMessages", varargs...)
	ret0, _ := ret[0].(*api.StudyMessages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantMessages indicates an expected call of GetParticipantMessages.
func (mr *MockStudyServiceApiClientMockRecorder) GetParticipantMessages(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantMessages", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetParticipantMessages), varargs...)
}

// GetParticipantStateByID mocks base method.
func (m *MockStudyServiceApiClient) GetParticipantStateByID(ctx context.Context, in *api.ParticipantStateByIDQuery, opts ...grpc.CallOption) (*api.ParticipantState, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParticipantStateByID", varargs...)
	ret0, _ := ret[0].(*api.ParticipantState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantStateByID indicates an expected call of GetParticipantStateByID.
func (mr *MockStudyServiceApiClientMockRecorder) GetParticipantStateByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantStateByID", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetParticipantStateByID), varargs...)
}

// GetParticipantStatesWithPagination mocks base method.
func (m *MockStudyServiceApiClient) GetParticipantStatesWithPagination(ctx context.Context, in *api.GetPStatesWithPaginationQuery, opts ...grpc.CallOption) (*api.ParticipantStatesWithPagination, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParticipantStatesWithPagination", varargs...)
	ret0, _ := ret[0].(*api.ParticipantStatesWithPagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantStatesWithPagination indicates an expected call of GetParticipantStatesWithPagination.
func (mr *MockStudyServiceApiClientMockRecorder) GetParticipantStatesWithPagination(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantStatesWithPagination", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetParticipantStatesWithPagination), varargs...)
}

// GetReportsForUser mocks base method.
func (m *MockStudyServiceApiClient) GetReportsForUser(ctx context.Context, in *api.GetReportsForUserReq, opts ...grpc.CallOption) (*api.ReportHistory, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReportsForUser", varargs...)
	ret0, _ := ret[0].(*api.ReportHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportsForUser indicates an expected call of GetReportsForUser.
func (mr *MockStudyServiceApiClientMockRecorder) GetReportsForUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportsForUser", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetReportsForUser), varargs...)
}

// GetResearcherMessages mocks base method.
func (m *MockStudyServiceApiClient) GetResearcherMessages(ctx context.Context, in *api.GetReseacherMessagesReq, opts ...grpc.CallOption) (*api.StudyMessages, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResearcherMessages", varargs...)
	ret0, _ := ret[0].(*api.StudyMessages)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResearcherMessages indicates an expected call of GetResearcherMessages.
func (mr *MockStudyServiceApiClientMockRecorder) GetResearcherMessages(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResearcherMessages", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetResearcherMessages), varargs...)
}

// GetResearcherNotificationSubscriptions mocks base method.
func (m *MockStudyServiceApiClient) GetResearcherNotificationSubscriptions(ctx context.Context, in *api.GetResearcherNotificationSubscriptionsReq, opts ...grpc.CallOption) (*api.NotificationSubscriptions, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResearcherNotificationSubscriptions", varargs...)
	ret0, _ := ret[0].(*api.NotificationSubscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResearcherNotificationSubscriptions indicates an expected call of GetResearcherNotificationSubscriptions.
func (mr *MockStudyServiceApiClientMockRecorder) GetResearcherNotificationSubscriptions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResearcherNotificationSubscriptions", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetResearcherNotificationSubscriptions), varargs...)
}

// GetResponsesFlatJSON mocks base method.
func (m *MockStudyServiceApiClient) GetResponsesFlatJSON(ctx context.Context, in *api.ResponseExportQuery, opts ...grpc.CallOption) (api.StudyServiceApi_GetResponsesFlatJSONClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResponsesFlatJSON", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_GetResponsesFlatJSONClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponsesFlatJSON indicates an expected call of GetResponsesFlatJSON.
func (mr *MockStudyServiceApiClientMockRecorder) GetResponsesFlatJSON(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponsesFlatJSON", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetResponsesFlatJSON), varargs...)
}

// GetResponsesFlatJSONWithPagination mocks base method.
func (m *MockStudyServiceApiClient) GetResponsesFlatJSONWithPagination(ctx context.Context, in *api.ResponseExportQuery, opts ...grpc.CallOption) (api.StudyServiceApi_GetResponsesFlatJSONWithPaginationClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResponsesFlatJSONWithPagination", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_GetResponsesFlatJSONWithPaginationClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponsesFlatJSONWithPagination indicates an expected call of GetResponsesFlatJSONWithPagination.
func (mr *MockStudyServiceApiClientMockRecorder) GetResponsesFlatJSONWithPagination(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponsesFlatJSONWithPagination", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetResponsesFlatJSONWithPagination), varargs...)
}

// GetResponsesLongFormatCSV mocks base method.
func (m *MockStudyServiceApiClient) GetResponsesLongFormatCSV(ctx context.Context, in *api.ResponseExportQuery, opts ...grpc.CallOption) (api.StudyServiceApi_GetResponsesLongFormatCSVClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResponsesLongFormatCSV", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_GetResponsesLongFormatCSVClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponsesLongFormatCSV indicates an expected call of GetResponsesLongFormatCSV.
func (mr *MockStudyServiceApiClientMockRecorder) GetResponsesLongFormatCSV(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponsesLongFormatCSV", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetResponsesLongFormatCSV), varargs...)
}

// GetResponsesWideFormatCSV mocks base method.
func (m *MockStudyServiceApiClient) GetResponsesWideFormatCSV(ctx context.Context, in *api.ResponseExportQuery, opts ...grpc.CallOption) (api.StudyServiceApi_GetResponsesWideFormatCSVClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetResponsesWideFormatCSV", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_GetResponsesWideFormatCSVClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponsesWideFormatCSV indicates an expected call of GetResponsesWideFormatCSV.
func (mr *MockStudyServiceApiClientMockRecorder) GetResponsesWideFormatCSV(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponsesWideFormatCSV", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetResponsesWideFormatCSV), varargs...)
}

// GetStudiesForUser mocks base method.
func (m *MockStudyServiceApiClient) GetStudiesForUser(ctx context.Context, in *api.GetStudiesForUserReq, opts ...grpc.CallOption) (*api.StudiesForUser, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStudiesForUser", varargs...)
	ret0, _ := ret[0].(*api.StudiesForUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudiesForUser indicates an expected call of GetStudiesForUser.
func (mr *MockStudyServiceApiClientMockRecorder) GetStudiesForUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudiesForUser", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetStudiesForUser), varargs...)
}

// GetStudiesWithPendingParticipantMessages mocks base method.
func (m *MockStudyServiceApiClient) GetStudiesWithPendingParticipantMessages(ctx context.Context, in *api.GetStudiesWithPendingParticipantMessagesReq, opts ...grpc.CallOption) (*api.Studies, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStudiesWithPendingParticipantMessages", varargs...)
	ret0, _ := ret[0].(*api.Studies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudiesWithPendingParticipantMessages indicates an expected call of GetStudiesWithPendingParticipantMessages.
func (mr *MockStudyServiceApiClientMockRecorder) GetStudiesWithPendingParticipantMessages(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudiesWithPendingParticipantMessages", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetStudiesWithPendingParticipantMessages), varargs...)
}

// GetStudy mocks base method.
func (m *MockStudyServiceApiClient) GetStudy(ctx context.Context, in *api.StudyReferenceReq, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStudy", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudy indicates an expected call of GetStudy.
func (mr *MockStudyServiceApiClientMockRecorder) GetStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetStudy), varargs...)
}

// GetStudyResponseStatistics mocks base method.
func (m *MockStudyServiceApiClient) GetStudyResponseStatistics(ctx context.Context, in *api.SurveyResponseQuery, opts ...grpc.CallOption) (*api.StudyResponseStatistics, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStudyResponseStatistics", varargs...)
	ret0, _ := ret[0].(*api.StudyResponseStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyResponseStatistics indicates an expected call of GetStudyResponseStatistics.
func (mr *MockStudyServiceApiClientMockRecorder) GetStudyResponseStatistics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyResponseStatistics", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetStudyResponseStatistics), varargs...)
}

// GetStudyRulesHistory mocks base method.
func (m *MockStudyServiceApiClient) GetStudyRulesHistory(ctx context.Context, in *api.StudyRulesHistoryReq, opts ...grpc.CallOption) (*api.StudyRulesHistory, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStudyRulesHistory", varargs...)
	ret0, _ := ret[0].(*api.StudyRulesHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyRulesHistory indicates an expected call of GetStudyRulesHistory.
func (mr *MockStudyServiceApiClientMockRecorder) GetStudyRulesHistory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyRulesHistory", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetStudyRulesHistory), varargs...)
}

// GetStudySurveyInfos mocks base method.
func (m *MockStudyServiceApiClient) GetStudySurveyInfos(ctx context.Context, in *api.StudyReferenceReq, opts ...grpc.CallOption) (*api.SurveyInfoResp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStudySurveyInfos", varargs...)
	ret0, _ := ret[0].(*api.SurveyInfoResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudySurveyInfos indicates an expected call of GetStudySurveyInfos.
func (mr *MockStudyServiceApiClientMockRecorder) GetStudySurveyInfos(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudySurveyInfos", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetStudySurveyInfos), varargs...)
}

// GetSurveyDefForStudy mocks base method.
func (m *MockStudyServiceApiClient) GetSurveyDefForStudy(ctx context.Context, in *api.SurveyVersionReferenceRequest, opts ...grpc.CallOption) (*api.Survey, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSurveyDefForStudy", varargs...)
	ret0, _ := ret[0].(*api.Survey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurveyDefForStudy indicates an expected call of GetSurveyDefForStudy.
func (mr *MockStudyServiceApiClientMockRecorder) GetSurveyDefForStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurveyDefForStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetSurveyDefForStudy), varargs...)
}

// GetSurveyInfoPreview mocks base method.
func (m *MockStudyServiceApiClient) GetSurveyInfoPreview(ctx context.Context, in *api.SurveyInfoExportQuery, opts ...grpc.CallOption) (*api.SurveyInfoExport, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSurveyInfoPreview", varargs...)
	ret0, _ := ret[0].(*api.SurveyInfoExport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurveyInfoPreview indicates an expected call of GetSurveyInfoPreview.
func (mr *MockStudyServiceApiClientMockRecorder) GetSurveyInfoPreview(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurveyInfoPreview", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetSurveyInfoPreview), varargs...)
}

// GetSurveyInfoPreviewCSV mocks base method.
func (m *MockStudyServiceApiClient) GetSurveyInfoPreviewCSV(ctx context.Context, in *api.SurveyInfoExportQuery, opts ...grpc.CallOption) (api.StudyServiceApi_GetSurveyInfoPreviewCSVClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSurveyInfoPreviewCSV", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_GetSurveyInfoPreviewCSVClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurveyInfoPreviewCSV indicates an expected call of GetSurveyInfoPreviewCSV.
func (mr *MockStudyServiceApiClientMockRecorder) GetSurveyInfoPreviewCSV(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurveyInfoPreviewCSV", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetSurveyInfoPreviewCSV), varargs...)
}

// GetSurveyKeys mocks base method.
func (m *MockStudyServiceApiClient) GetSurveyKeys(ctx context.Context, in *api.GetSurveyKeysRequest, opts ...grpc.CallOption) (*api.SurveyKeys, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSurveyKeys", varargs...)
	ret0, _ := ret[0].(*api.SurveyKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurveyKeys indicates an expected call of GetSurveyKeys.
func (mr *MockStudyServiceApiClientMockRecorder) GetSurveyKeys(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurveyKeys", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetSurveyKeys), varargs...)
}

// GetSurveyVersionInfos mocks base method.
func (m *MockStudyServiceApiClient) GetSurveyVersionInfos(ctx context.Context, in *api.SurveyReferenceRequest, opts ...grpc.CallOption) (*api.SurveyVersions, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSurveyVersionInfos", varargs...)
	ret0, _ := ret[0].(*api.SurveyVersions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurveyVersionInfos indicates an expected call of GetSurveyVersionInfos.
func (mr *MockStudyServiceApiClientMockRecorder) GetSurveyVersionInfos(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurveyVersionInfos", reflect.TypeOf((*MockStudyServiceApiClient)(nil).GetSurveyVersionInfos), varargs...)
}

// HasParticipantStateWithCondition mocks base method.
func (m *MockStudyServiceApiClient) HasParticipantStateWithCondition(ctx context.Context, in *api.ProfilesWithConditionReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HasParticipantStateWithCondition", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasParticipantStateWithCondition indicates an expected call of HasParticipantStateWithCondition.
func (mr *MockStudyServiceApiClientMockRecorder) HasParticipantStateWithCondition(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasParticipantStateWithCondition", reflect.TypeOf((*MockStudyServiceApiClient)(nil).HasParticipantStateWithCondition), varargs...)
}

// LeaveStudy mocks base method.
func (m *MockStudyServiceApiClient) LeaveStudy(ctx context.Context, in *api.LeaveStudyMsg, opts ...grpc.CallOption) (*api.AssignedSurveys, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LeaveStudy", varargs...)
	ret0, _ := ret[0].(*api.AssignedSurveys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaveStudy indicates an expected call of LeaveStudy.
func (mr *MockStudyServiceApiClientMockRecorder) LeaveStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).LeaveStudy), varargs...)
}

// ProfileDeleted mocks base method.
func (m *MockStudyServiceApiClient) ProfileDeleted(ctx context.Context, in *api_types.TokenInfos, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProfileDeleted", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfileDeleted indicates an expected call of ProfileDeleted.
func (mr *MockStudyServiceApiClientMockRecorder) ProfileDeleted(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileDeleted", reflect.TypeOf((*MockStudyServiceApiClient)(nil).ProfileDeleted), varargs...)
}

// RegisterTemporaryParticipant mocks base method.
func (m *MockStudyServiceApiClient) RegisterTemporaryParticipant(ctx context.Context, in *api.RegisterTempParticipantReq, opts ...grpc.CallOption) (*api.RegisterTempParticipantResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterTemporaryParticipant", varargs...)
	ret0, _ := ret[0].(*api.RegisterTempParticipantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterTemporaryParticipant indicates an expected call of RegisterTemporaryParticipant.
func (mr *MockStudyServiceApiClientMockRecorder) RegisterTemporaryParticipant(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTemporaryParticipant", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RegisterTemporaryParticipant), varargs...)
}

// RemoveConfidentialResponsesForProfiles mocks base method.
func (m *MockStudyServiceApiClient) RemoveConfidentialResponsesForProfiles(ctx context.Context, in *api.RemoveConfidentialResponsesForProfilesReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveConfidentialResponsesForProfiles", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveConfidentialResponsesForProfiles indicates an expected call of RemoveConfidentialResponsesForProfiles.
func (mr *MockStudyServiceApiClientMockRecorder) RemoveConfidentialResponsesForProfiles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveConfidentialResponsesForProfiles", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RemoveConfidentialResponsesForProfiles), varargs...)
}

// RemoveStudyMember mocks base method.
func (m *MockStudyServiceApiClient) RemoveStudyMember(ctx context.Context, in *api.StudyMemberReq, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveStudyMember", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveStudyMember indicates an expected call of RemoveStudyMember.
func (mr *MockStudyServiceApiClientMockRecorder) RemoveStudyMember(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStudyMember", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RemoveStudyMember), varargs...)
}

// RemoveStudyRulesVersion mocks base method.
func (m *MockStudyServiceApiClient) RemoveStudyRulesVersion(ctx context.Context, in *api.StudyRulesVersionReferenceReq, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveStudyRulesVersion", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveStudyRulesVersion indicates an expected call of RemoveStudyRulesVersion.
func (mr *MockStudyServiceApiClientMockRecorder) RemoveStudyRulesVersion(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStudyRulesVersion", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RemoveStudyRulesVersion), varargs...)
}

// RemoveSurveyVersion mocks base method.
func (m *MockStudyServiceApiClient) RemoveSurveyVersion(ctx context.Context, in *api.SurveyVersionReferenceRequest, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveSurveyVersion", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveSurveyVersion indicates an expected call of RemoveSurveyVersion.
func (mr *MockStudyServiceApiClientMockRecorder) RemoveSurveyVersion(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSurveyVersion", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RemoveSurveyVersion), varargs...)
}

// RunRules mocks base method.
func (m *MockStudyServiceApiClient) RunRules(ctx context.Context, in *api.StudyRulesReq, opts ...grpc.CallOption) (*api.RuleRunSummary, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunRules", varargs...)
	ret0, _ := ret[0].(*api.RuleRunSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunRules indicates an expected call of RunRules.
func (mr *MockStudyServiceApiClientMockRecorder) RunRules(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRules", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RunRules), varargs...)
}

// RunRulesForPreviousResponses mocks base method.
func (m *MockStudyServiceApiClient) RunRulesForPreviousResponses(ctx context.Context, in *api.RunRulesForPreviousResponsesReq, opts ...grpc.CallOption) (*api.RuleRunSummary, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunRulesForPreviousResponses", varargs...)
	ret0, _ := ret[0].(*api.RuleRunSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunRulesForPreviousResponses indicates an expected call of RunRulesForPreviousResponses.
func (mr *MockStudyServiceApiClientMockRecorder) RunRulesForPreviousResponses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRulesForPreviousResponses", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RunRulesForPreviousResponses), varargs...)
}

// RunRulesForSingleParticipant mocks base method.
func (m *MockStudyServiceApiClient) RunRulesForSingleParticipant(ctx context.Context, in *api.RunRulesForSingleParticipantReq, opts ...grpc.CallOption) (*api.RuleRunSummary, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunRulesForSingleParticipant", varargs...)
	ret0, _ := ret[0].(*api.RuleRunSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunRulesForSingleParticipant indicates an expected call of RunRulesForSingleParticipant.
func (mr *MockStudyServiceApiClientMockRecorder) RunRulesForSingleParticipant(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRulesForSingleParticipant", reflect.TypeOf((*MockStudyServiceApiClient)(nil).RunRulesForSingleParticipant), varargs...)
}

// SaveStudyMember mocks base method.
func (m *MockStudyServiceApiClient) SaveStudyMember(ctx context.Context, in *api.StudyMemberReq, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveStudyMember", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveStudyMember indicates an expected call of SaveStudyMember.
func (mr *MockStudyServiceApiClientMockRecorder) SaveStudyMember(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudyMember", reflect.TypeOf((*MockStudyServiceApiClient)(nil).SaveStudyMember), varargs...)
}

// SaveStudyProps mocks base method.
func (m *MockStudyServiceApiClient) SaveStudyProps(ctx context.Context, in *api.StudyPropsReq, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveStudyProps", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveStudyProps indicates an expected call of SaveStudyProps.
func (mr *MockStudyServiceApiClientMockRecorder) SaveStudyProps(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudyProps", reflect.TypeOf((*MockStudyServiceApiClient)(nil).SaveStudyProps), varargs...)
}

// SaveStudyRules mocks base method.
func (m *MockStudyServiceApiClient) SaveStudyRules(ctx context.Context, in *api.StudyRulesReq, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveStudyRules", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveStudyRules indicates an expected call of SaveStudyRules.
func (mr *MockStudyServiceApiClientMockRecorder) SaveStudyRules(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudyRules", reflect.TypeOf((*MockStudyServiceApiClient)(nil).SaveStudyRules), varargs...)
}

// SaveStudyStatus mocks base method.
func (m *MockStudyServiceApiClient) SaveStudyStatus(ctx context.Context, in *api.StudyStatusReq, opts ...grpc.CallOption) (*api.Study, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveStudyStatus", varargs...)
	ret0, _ := ret[0].(*api.Study)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveStudyStatus indicates an expected call of SaveStudyStatus.
func (mr *MockStudyServiceApiClientMockRecorder) SaveStudyStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStudyStatus", reflect.TypeOf((*MockStudyServiceApiClient)(nil).SaveStudyStatus), varargs...)
}

// SaveSurveyToStudy mocks base method.
func (m *MockStudyServiceApiClient) SaveSurveyToStudy(ctx context.Context, in *api.AddSurveyReq, opts ...grpc.CallOption) (*api.Survey, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveSurveyToStudy", varargs...)
	ret0, _ := ret[0].(*api.Survey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSurveyToStudy indicates an expected call of SaveSurveyToStudy.
func (mr *MockStudyServiceApiClientMockRecorder) SaveSurveyToStudy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSurveyToStudy", reflect.TypeOf((*MockStudyServiceApiClient)(nil).SaveSurveyToStudy), varargs...)
}

// Status mocks base method.
func (m *MockStudyServiceApiClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Status", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockStudyServiceApiClientMockRecorder) Status(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStudyServiceApiClient)(nil).Status), varargs...)
}

// StreamParticipantFileInfos mocks base method.
func (m *MockStudyServiceApiClient) StreamParticipantFileInfos(ctx context.Context, in *api.FileInfoQuery, opts ...grpc.CallOption) (api.StudyServiceApi_StreamParticipantFileInfosClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamParticipantFileInfos", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_StreamParticipantFileInfosClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamParticipantFileInfos indicates an expected call of StreamParticipantFileInfos.
func (mr *MockStudyServiceApiClientMockRecorder) StreamParticipantFileInfos(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamParticipantFileInfos", reflect.TypeOf((*MockStudyServiceApiClient)(nil).StreamParticipantFileInfos), varargs...)
}

// StreamParticipantStates mocks base method.
func (m *MockStudyServiceApiClient) StreamParticipantStates(ctx context.Context, in *api.ParticipantStateQuery, opts ...grpc.CallOption) (api.StudyServiceApi_StreamParticipantStatesClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamParticipantStates", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_StreamParticipantStatesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamParticipantStates indicates an expected call of StreamParticipantStates.
func (mr *MockStudyServiceApiClientMockRecorder) StreamParticipantStates(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamParticipantStates", reflect.TypeOf((*MockStudyServiceApiClient)(nil).StreamParticipantStates), varargs...)
}

// StreamReportHistory mocks base method.
func (m *MockStudyServiceApiClient) StreamReportHistory(ctx context.Context, in *api.ReportHistoryQuery, opts ...grpc.CallOption) (api.StudyServiceApi_StreamReportHistoryClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamReportHistory", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_StreamReportHistoryClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamReportHistory indicates an expected call of StreamReportHistory.
func (mr *MockStudyServiceApiClientMockRecorder) StreamReportHistory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamReportHistory", reflect.TypeOf((*MockStudyServiceApiClient)(nil).StreamReportHistory), varargs...)
}

// StreamStudyResponses mocks base method.
func (m *MockStudyServiceApiClient) StreamStudyResponses(ctx context.Context, in *api.SurveyResponseQuery, opts ...grpc.CallOption) (api.StudyServiceApi_StreamStudyResponsesClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamStudyResponses", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_StreamStudyResponsesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamStudyResponses indicates an expected call of StreamStudyResponses.
func (mr *MockStudyServiceApiClientMockRecorder) StreamStudyResponses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamStudyResponses", reflect.TypeOf((*MockStudyServiceApiClient)(nil).StreamStudyResponses), varargs...)
}

// SubmitResponse mocks base method.
func (m *MockStudyServiceApiClient) SubmitResponse(ctx context.Context, in *api.SubmitResponseReq, opts ...grpc.CallOption) (*api.AssignedSurveys, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitResponse", varargs...)
	ret0, _ := ret[0].(*api.AssignedSurveys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitResponse indicates an expected call of SubmitResponse.
func (mr *MockStudyServiceApiClientMockRecorder) SubmitResponse(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitResponse", reflect.TypeOf((*MockStudyServiceApiClient)(nil).SubmitResponse), varargs...)
}

// UnpublishSurvey mocks base method.
func (m *MockStudyServiceApiClient) UnpublishSurvey(ctx context.Context, in *api.SurveyReferenceRequest, opts ...grpc.CallOption) (*api.ServiceStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnpublishSurvey", varargs...)
	ret0, _ := ret[0].(*api.ServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpublishSurvey indicates an expected call of UnpublishSurvey.
func (mr *MockStudyServiceApiClientMockRecorder) UnpublishSurvey(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishSurvey", reflect.TypeOf((*MockStudyServiceApiClient)(nil).UnpublishSurvey), varargs...)
}

// UpdateResearcherNotificationSubscriptions mocks base method.
func (m *MockStudyServiceApiClient) UpdateResearcherNotificationSubscriptions(ctx context.Context, in *api.UpdateResearcherNotificationSubscriptionsReq, opts ...grpc.CallOption) (*api.NotificationSubscriptions, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateResearcherNotificationSubscriptions", varargs...)
	ret0, _ := ret[0].(*api.NotificationSubscriptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResearcherNotificationSubscriptions indicates an expected call of UpdateResearcherNotificationSubscriptions.
func (mr *MockStudyServiceApiClientMockRecorder) UpdateResearcherNotificationSubscriptions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResearcherNotificationSubscriptions", reflect.TypeOf((*MockStudyServiceApiClient)(nil).UpdateResearcherNotificationSubscriptions), varargs...)
}

// UploadParticipantFile mocks base method.
func (m *MockStudyServiceApiClient) UploadParticipantFile(ctx context.Context, opts ...grpc.CallOption) (api.StudyServiceApi_UploadParticipantFileClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadParticipantFile", varargs...)
	ret0, _ := ret[0].(api.StudyServiceApi_UploadParticipantFileClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadParticipantFile indicates an expected call of UploadParticipantFile.
func (mr *MockStudyServiceApiClientMockRecorder) UploadParticipantFile(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadParticipantFile", reflect.TypeOf((*MockStudyServiceApiClient)(nil).UploadParticipantFile), varargs...)
}
